### PR TITLE
First pass at sustainability page.

### PR DESCRIPTION
**Pull request by grugnog**

### CODE REVIEW

**Comment by grugnog** [comment]
Working on a build issue with Strapi, so haven't tested and not sure if this will build or not, but wanted to save progress at least!

**Comment by TheBoatyMcBoatFace** [comment]
I just [updated the copy](https://github.com/CivicActions/civicactions-homesite/pull/266/commits/41d36a03937db6711ed6966260443c5f23df0ad5) to the most recent version, [made the 2 in CO2 subscript](https://github.com/CivicActions/civicactions-homesite/pull/266/commits/fa9e375f2a5414556d379da154d1459de039a98d), and [added some links](https://github.com/CivicActions/civicactions-homesite/pull/266/commits/af48f79bcf33babd6cbdce7a17e4e25b421b6791) which seemed like a good fit. @mgifford let me know if I need to take those links out. Also, we are dealing with some Strapi connectivity issues and that is holding up progress on a layout fix.

**Review by mgifford — COMMENTED** [review]
FYI

**Review by mgifford — APPROVED** [review]
Looks good now. Thanks.

**Pull request merged**
