### PR TITLE
Upgrade Application to Gatsby 5

### PR DESCRIPTION
**Pull request by brentonkelly1982**
## What's Changed
- Upgraded Gatsby to version 5.
- Updated all dependencies to latest versions.
- Adjusted GraphQL queries as needed for the upgrade.
- Fixed broken data references from GraphQL.
- Added some resolvers for some of the Strapi API fields.
- Updated Strapi config.
- Fixed broken pages.
- Replaced react-helmet with Gatsby Head API.
- Fixed various minor React and Gatsby errors.

## Start Up Locally
1. Run `yarn install`.
2. Confirm that .env file exists with correct credentials from Owen. Then run `source .env`.
3. Run `npm run start`.

### CODE REVIEW

**Comment by dcgoodwin2112** [comment]
On first install attempt, I received an error that the src/images directory did not exist. I added it manually and the install completed successfully after that

**Comment by dcgoodwin2112** [comment]
the `/team` page appears to be a bit out of date. May just need fresh content import in Strapi

**Comment by dcgoodwin2112** [comment]
The tab box on the `/services/ditap` page appears to be broken

Screenshot 2023-10-11 at 3 58 50 PM

**Comment by dcgoodwin2112** [comment]
Seeing 404 errors on the favicon

Screenshot 2023-10-11 at 4 11 28 PM
icon image

**Comment by grugnog** [comment]
> On first install attempt, I received an error that the src/images directory did not exist. I added it manually and the install completed successfully after that

Resolved this one by committing a stub images folder (containing only a .gitignore)

**Comment by grugnog** [comment]
> the `/team` page appears to be a bit out of date. May just need fresh content import in Strapi

Also resolved this one by rerunning the Strapi upgrade

**Comment by grugnog** [comment]
It looks like body field content is missing on the press page:
image

**Comment by grugnog** [comment]
It looks like we are including draft content in the case study pages (the drafts help avoid missing field issues in Gatsby) - we should be able to filter these out.
image

**Comment by brentonkelly1982** [comment]
- Fixed broken favicon.
- Fixed broken press body.
- Fixed missing child key prop on child elements.
- Fixed tabs on /services/ditap.

**Comment by grugnog** [comment]
@brentonkelly1982 @dcgoodwin2112 there is something up with Calvin's profile photo. Originally there was an image format warning message in the build logs, but I replaced the image (first with ta fresh JPG export, then a PNG) - the warning went away, but the image is still missing. I just deleted the Github Actions build cache and rebuilt, but still no joy... wondering if you have any ideas?
https://ca-it-prod-home-5918--pr242-gatsby-5-upgrade-1vdx7lsh.web.app/team/

**Comment by brentonkelly1982** [comment]
> @brentonkelly1982 @dcgoodwin2112 there is something up with Calvin's profile photo. Originally there was an image format warning message in the build logs, but I replaced the image (first with ta fresh JPG export, then a PNG) - the warning went away, but the image is still missing. I just deleted the Github Actions build cache and rebuilt, but still no joy... wondering if you have any ideas? https://ca-it-prod-home-5918--pr242-gatsby-5-upgrade-1vdx7lsh.web.app/team/

Looking on the frontend, there are no errors and there is no image data rendering at all in the DOM as if an image has not been uploaded for Calvin. Are you able to share what things look like inside Strapi?

**Comment by dcgoodwin2112** [comment]
@brentonkelly1982 @grugnog I ran gatsby clean on my local and restarted the dev server. His appears is showing up for me on my local now. 

```
npm run clean
npm run develop
```

**Comment by grugnog** [comment]
@brentonkelly1982 @dcgoodwin2112 thanks - let me try some more aggressive cache/data clearing (going to try deleting the deploy also) and see if that helps

**Comment by grugnog** [comment]
@brentonkelly1982 @dcgoodwin2112 Hmm - that didn't help, neither did a [totally fresh review environment](https://ca-it-prod-home-5918--pr243-gatsby-5-upgrade-tes-gr2uj992.web.app/team/) built from #243. Unless there is some other cache or data persistence happening that I am unaware of there I am wondering if there is some subtle environmental issue going on?

It does seem to be coming from the Gatsby build, as the image is missing in the HTML:
```
curl https://ca-it-prod-home-5918--pr243-gatsby-5-upgrade-tes-gr2uj992.web.app/team/ | htmlq -p '.section__teaser-grid > div:nth-child(25), .section__teaser-grid > div:nth-child(26)'
<div class="teaser-grid--wrapper">
  <div class="teaser-grid">
    <div class="teaser-grid__name teaser__link">
      <div class="teaser-grid__image">
        <div class="gatsby-image-wrapper gatsby-image-wrapper-constrained" data-gatsby-image-wrapper="">
          <div style="max-width:264px;display:block"><img alt="" aria-hidden="true" role="presentation" src="data:image/svg+xml;charset=utf-8,%3Csvg%20height='264'%20width='264'%20xmlns='http://www.w3.org/2000/svg'%20version='1.1'%3E%3C/svg%3E" style="max-width:100%;display:block;position:static">
          </div>
          <img alt="" aria-hidden="true" data-placeholder-image="" decoding="async" src="data:image/jpeg...snip
        </div>
      </div>
      <div class="teaser-grid__text">
        <div class="teaser-grid__title">
          Bridgette Golson
        </div>
        <div class="teaser-grid__role">
          QA Engineer
        </div>
      </div>
    </div>
  </div>
</div>
<div class="teaser-grid--wrapper">
  <div class="teaser-grid">
    <div class="teaser-grid__name teaser__link">
      <div class="teaser-grid__image">
      </div>
      <div class="teaser-grid__text">
        <div class="teaser-grid__title">
          Calvin Williams
        </div>
        <div class="teaser-grid__role">
          Program Manager
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by dcgoodwin2112** [comment]
@grugnog  Struggling to come up with ideas here, but could we maybe try deleting Calvin's content node and image and re-adding them?

**Comment by brentonkelly1982** [comment]
> @grugnog Struggling to come up with ideas here, but could we maybe try deleting Calvin's content node and image and re-adding them?

@grugnog Same here and I would try the same. When I was editing the tab sections content under Offering to make sure it was working properly, Strapi was duplicating all three tabs when I would save. It was really strange and the only way that I was able to get it corrected was to delete all of the tabs and rebuild them fresh.

Is this issue happening when editing another team member?

**Review by grugnog — APPROVED** [review]
Fixed a few minor things that were pretty straightfoward and did some testing - can't find any more differences to the production site so I think this is all ready - thank you!

**Pull request merged**
