### PR TITLE
Services CTA & Responsiveness

### PR DESCRIPTION
**Pull request by Yodart**
@iris-i For some reason, this was not merged into the main branch. I think that this `services.content` branch just was never merged to main (or `/homepage`) even tho the responsiveness was reviewed and merged from `services.responsivesses` to `services.ctas` on #12 then `services.ctas` itself was then reviewed and merged into `services.content` that I believe just end up never being merged

### CODE REVIEW

**Review by iris-i — APPROVED** [review]

**Comment by iris-i** [comment]
@Yodart This looks good but has a merge conflict.

**Comment by Yodart** [comment]
Was just an import conflict. Ready to roll now @iris-i !

**Review by iris-i — APPROVED** [review]

**Comment by iris-i** [comment]
@Yodart mind taking another look? It still seems to have a merge conflict on services.js.

**Comment by Yodart** [comment]
> @Yodart mind taking another look? It still seems to have a merge conflict on services.js.

I don't see any other conflicts, am I missing something?

**Pull request merged**
