### PR TITLE
Homer-447 Contracting page build and styling

### PR DESCRIPTION
**Pull request by jaube05**

### CODE REVIEW

**Review by iris-i — CHANGES_REQUESTED** [review]
@jaube05 this looks good, it needs a couple of tweaks.
The `.inner` wrapper for this section needs some padding in mobile:

Screen Shot 2021-06-02 at 11 21 52 AM

The red header doesn't quite match the design comp. We may want to move this into a different ticket, it seems to affect other pages with the red hero.

Screen Shot 2021-06-02 at 11 22 27 AM

**Comment by jaube05** [comment]
Created a ticket for red header diagonal issue.

**Comment by jaube05** [comment]
Was able to fix header, (was easier than expected). and padding on mobile for dark mint green section

**Review by iris-i — APPROVED** [review]

**Comment by iris-i** [comment]
@jaube05, I added a few mobile styles for the contracting awards section. I made some assumptions about how it should look since there's no mobile comp.

**Pull request merged**
