### PR TITLE
Homer-344 404 Pages design qa feedback

### PR DESCRIPTION
**Pull request by jaube05**

### CODE REVIEW

**Review by iris-i — COMMENTED** [review]
This looks good @jaube05. A couple of minor changes might be needed.

**Review by iris-i — CHANGES_REQUESTED** [review]
Visual review feedback:
The homepage lost some styles in the Case studies section and the Red buttons in each section. Text-color is black instead of white.

**Comment by jaube05** [comment]
Addressed the feedback @iris-i But for the homepage I don't see any styling changes or red button with black text??? Maybe it was cached, or I fixed it already?

**Review by iris-i — APPROVED** [review]

**Comment by iris-i** [comment]
This looks great @jaube05! 
You're right, I don't see the homepage styling differences any longer. Must've been cache.

**Pull request merged**
