### PR TITLE
Add Bluesky social link

### PR DESCRIPTION
**Pull request by TheBoatyMcBoatFace**
Added Bluesky footer links. I can't figure out how to get the local preview env setup, so I haven't been able to confirm that this works. The only part I am _worried_ about is the icon style.

### CODE REVIEW

**Comment by TheBoatyMcBoatFace** [comment]
Git is dumb. My changes to data.js didn't properly commit. Hold on this until new commit is pushed

**Comment by TheBoatyMcBoatFace** [comment]
**Additional Info**

[Slack Convo](https://civicactions.slack.com/archives/C029P6NJZ/p1733327366042789)

**Comment by TheBoatyMcBoatFace** [comment]
If you have bandwidth, can you review @dmundra?

**Review by dmundra — APPROVED** [review]
Looks good for the most part. A nitpick I noticed on Chrome+Mac the Bluesky and Twitter icons bottom curve is higher than Vimeo and LinkedIn. Not sure why that is happening as I can see the values of the images are the same. Screenshot using a random Mac window as a ruler to see that differences:

Icons displayed on Chrome on a Mac

**Comment by TheBoatyMcBoatFace** [comment]
Thank you @dmundra for catching that. I'll update the SVG. I had to create the icon from scratch, so my sizes seem to be a little off. I'll get that updated and push a hotfix once it is done. Thank you again!

**Comment by openprivacy** [comment]
@TheBoatyMcBoatFace Small nit (maybe intentional?): the footer Vimeo, Bluesky and Linkedin icons become blue on mouse-over, but the X/Twitter icon does not.

**Pull request merged**
